// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ParcialTarea;

namespace ParcialTarea.Migrations
{
    [DbContext(typeof(TareasDbContext))]
    partial class TareasDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8");

            modelBuilder.Entity("ParcialTarea.Detalle", b =>
                {
                    b.Property<int>("IdDetalles")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Fecha")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(8);

                    b.Property<int>("IdRecurso")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RecursoIdRecursos")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tiempo")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(4);

                    b.HasKey("IdDetalles");

                    b.HasIndex("RecursoIdRecursos");

                    b.ToTable("Detalle");
                });

            modelBuilder.Entity("ParcialTarea.Recurso", b =>
                {
                    b.Property<int>("IdRecursos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("UsuarioIdUsuario")
                        .HasColumnType("INTEGER");

                    b.Property<int>("idUsuario")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdRecursos");

                    b.HasIndex("UsuarioIdUsuario");

                    b.ToTable("Recurso");
                });

            modelBuilder.Entity("ParcialTarea.Tarea", b =>
                {
                    b.Property<int>("IdTareas")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Estado")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Estimacion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("IdResponsable")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ResponsableIdRecursos")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Vencimiento")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IdTareas");

                    b.HasIndex("ResponsableIdRecursos");

                    b.ToTable("Tarea");
                });

            modelBuilder.Entity("ParcialTarea.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(10);

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(10);

                    b.HasKey("IdUsuario");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("ParcialTarea.Detalle", b =>
                {
                    b.HasOne("ParcialTarea.Recurso", "Recurso")
                        .WithMany()
                        .HasForeignKey("RecursoIdRecursos");
                });

            modelBuilder.Entity("ParcialTarea.Recurso", b =>
                {
                    b.HasOne("ParcialTarea.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioIdUsuario");
                });

            modelBuilder.Entity("ParcialTarea.Tarea", b =>
                {
                    b.HasOne("ParcialTarea.Recurso", "Responsable")
                        .WithMany()
                        .HasForeignKey("ResponsableIdRecursos");
                });
#pragma warning restore 612, 618
        }
    }
}
